### ISSUE TITLE
[Feature Request] 1.36 Cooling progress when pouring nitrogen (By Dr.Chen)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#10]
**Describe the Request:**

 I can pour liquid nitrogen into the station, but the cooling progess does not change.

**Comment by smallelephant9516** [comment]
More detail is needed because I never meet this problem after many times of testing. Maybe the liquid nitrogen dewar is too far away from the work station. Then, it is the same problem with #14

**Comment by SchubyDong** [comment]
This problem has been solved as what we talked about during the meeting. The UI will pop up while the dewar is close to the workstation but the progress will continue after pouring LN
