### ISSUE TITLE
Not 100 score even strictly follow the procedures 

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#103]
Hi, I still could not get 100/100 score even if I follow the all steps strictly from the tutorial mode recorded video.
 
![image](https://user-images.githubusercontent.com/52638056/139735826-3824e89d-c31d-45c5-9328-977dfa4baaab.png)

**Comment by smallelephant9516** [comment]
Also, there is no error report output after I finish it.

**Comment by SchubyDong** [comment]
Now I have fixed this issue.You can get 100 score with the correct operation sequence.
