### ISSUE TITLE
Item replacement

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#112]
In the step of grabbing the grid box using the tweezer, if we accidentally touch the blotting paper, it will attach to the blotting paper but the grid box will disappear.

**Comment by smallelephant9516** [comment]
In the vive version, it will still be overlap but not replaced by the gridbox

**Comment by smallelephant9516** [comment]
It is still a problem, 2 blotting paper overlap.
![image](https://user-images.githubusercontent.com/52638056/169131564-b24ca177-9240-45cc-abaf-96610570165d.jpeg)

**Comment by SchubyDong** [comment]
This bug has been fixed and updated in our oculus version
