### ISSUE TITLE
Workstation flip

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#118]
On the last step when I put the workstation from vitrobot back to the hood. When I try to grab it, the workstation is hard to grab and also it flips when I grab it![image](https://user-images.githubusercontent.com/52638056/169105924-f37f4516-2b30-4663-87fb-75a43e70efe4.jpeg)

**Comment by SchubyDong** [comment]
I met it once and tried to duplicate this bug but failed. Would you please offer me how you make this happen?
