### ISSUE TITLE
[Experience] 1.36 Something too transparent (By Dr.Chen)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#12]
**Describe the Experience:**

Some transparent object is way too transparent - there is a pan with a cap. The cap is a solid transparent object. Need to add some details to make it look right.

**Comment by SchubyDong** [comment]
We redesigned the texture of some object and adjust the light at the same time

**Comment by smallelephant9516** [comment]
This problem is fixed. The texture and color of the petri dish are changed. But I think it is too dark now, before is actually more realistic.

**Comment by Wandayu** [comment]
In the version 1.38, the smoke coming out of the ethene tank's tip is black, so it looks like the instrument is broken. Of course I can understand it's to make it less transparent.
