### ISSUE TITLE
Cleaning up the humidifier

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#120]
It is hard to finish this step, even if I try to shake it hard.![image](https://user-images.githubusercontent.com/52638056/169106593-aa7088a3-cfe4-4a18-9f58-382dd3fccc9e.jpeg)

**Comment by SchubyDong** [comment]
I have created another detection. For safety I didn't publish it in our current oculus version. But you can try with the inner test apk file

**Comment by smallelephant9516** [comment]
Thanks for your updating, is it means that this would not be solved currently in the oculus version?
