### ISSUE TITLE
The dewar disappear

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#122]
When I drop the dewar during the time of adding liquid nitrogen, the dewar fly away
![image](https://user-images.githubusercontent.com/52638056/169130947-31024aa2-9e13-485f-b58f-7d111d362600.jpeg)

**Comment by SchubyDong** [comment]
We need some clue how it happens

**Comment by smallelephant9516** [comment]
It happens not often, probably because the returning function not working very well, close at the moment
