### ISSUE TITLE
The grid box cannot be take out from the workstation

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#127]
![70](https://user-images.githubusercontent.com/52638056/179385775-c4380333-3e34-4ed8-9cd0-e992fc70cd55.jpg)

**Comment by smallelephant9516** [comment]
It happens more often when we do it slower

**Comment by smallelephant9516** [comment]
![image](https://user-images.githubusercontent.com/52638056/180620986-c7635bd0-ecf9-4807-975f-20ad91c50f16.png)

**Comment by smallelephant9516** [comment]
This is still a problem

**Comment by SchubyDong** [comment]
This bug has been fixed in the newest version

**Comment by SchubyDong** [comment]
This is a weird one since it works well on the PC version. Please try it on different helmets

**Comment by smallelephant9516** [comment]
Fixed now
