### ISSUE TITLE
Vitrobot Exam mood

### ISSUE THREAD

**Issue by Abayomi-Adegboyega** [CryoVR/CryoVR_Vitrobot#143]
Please kindly check the exam mode of vitrobot, it has stopped working.
Thanks

**Comment by Abayomi-Adegboyega** [comment]
> Please kindly check the exam mode of vitrobot, it has stopped working.
> 
> Thanks

![image](https://github.com/CryoVR/CryoVR_Vitrobot/assets/107444436/71d7db30-47fe-4468-923f-ab57387bf9ee)

**Comment by Abayomi-Adegboyega** [comment]
https://github.com/CryoVR/CryoVR_Vitrobot/assets/107444436/705acede-70d8-4293-acbe-8d7240221661

**Comment by Abayomi-Adegboyega** [comment]
![image](https://github.com/CryoVR/CryoVR_Vitrobot/assets/107444436/2a9d9ab4-ca33-411b-ba46-a0e6c8acc6a1)

**Comment by SchubyDong** [comment]
If you exit the exam mode without getting a 100% score, you will still get a code but the code won't give you the certificate. In the next patch, I will hide the code if the user doesn't pass to avoid misleading. But for now, it won't stop you from finishing the entire exam mode.

**Comment by Abayomi-Adegboyega** [comment]
Okay, thank you
