### ISSUE TITLE
[Feature Request] 1.36 Indications of how to operate the regulator valve (By Dr.Schmid)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#15]
**Describe the Request:**

Ethane: turning on the tank valve works, but there is no indication of when and/or how, to turn on the small regulator valve. This was there, even though awkward, in the CP3 VR.

**Comment by smallelephant9516** [comment]
It is the same problem for the vitrobot, lack the UI or voice indication on how to turn on the small regulator valve.

**Comment by SchubyDong** [comment]
We have recorded a new sound instruction for it. What's more, the new sound was placed in wrong steps in V1.40, and we have fixed this bug in our V1.41 files.
