### ISSUE TITLE
[Experience] 1.36 Unclear how to handle with the ethane tip (By Dr.Schmid)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#16]
**Describe the Experience:**

As in the CP3 VR, it’s unclear whether the ethane tip has to be held by hand through the ethane cup filling procedure, or whether one rests it in the ethane cup and lets go.

**Comment by SchubyDong** [comment]
We will improve the content of the text and voice description to make it more clear.

**Comment by smallelephant9516** [comment]
It is also not clearly indicated in the vitrobot VR

**Comment by smallelephant9516** [comment]
Still need to fix voice description on the vitrobot

**Comment by SchubyDong** [comment]
This question is solved as we claimed in question #15
