### ISSUE TITLE
[Experience] 1.36 Requires two hands to operate when opening the port (By Dr.Schmid)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#17]
**Describe the Experience:**

The most awkward maneuver of the whole operation is, after one has filled the pipette with the sample (with the right hand, of course), one has to open the port, on the right hand side of the Vitrobot, with the left hand!

**Comment by SchubyDong** [comment]
We may need a standard interaction way in real life. Will send an email to Dr. Schmid to ask how he operates the instrument with this step

**Comment by smallelephant9516** [comment]
Brenda will email Dr Schmid once we have a major release

**Comment by gonzalb908** [comment]
This is something that may vary depending on user preference. So far, we have found videos and have personal experience with operating this instrument differently than Dr. Schmid has mentioned.
