### ISSUE TITLE
[Experience] 1.36 Confues about the interaction with the screen (By Dr.Schmid)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#18]
**Desribe the Experience:**

When, how many times, and for what purposes, one pushes the screen with the stylus, was a bit confusing.

**Comment by smallelephant9516** [comment]
I think the voice, text, and UI indication is clear. It is one click to raise the plunger and one-click for plunging. So, the current procedure is a reasonable but very simplified procedure for the screen operation.

**Comment by smallelephant9516** [comment]
Text instruction has been fixed. Still need the voice instructions.

**Comment by smallelephant9516** [comment]
Also, please remove the error once we click the continue button. There is one suggestion from Brenda and I think it's good. It is that once we click the continue, we could pop up with an UI or the text instruction saying that continue watching the vitrobot operation.

**Comment by SchubyDong** [comment]
It's a good suggestion, I will manage to achieve this function

**Comment by SchubyDong** [comment]
Now the Highlighted plane and arrow will disappear once the button is clicked by the stylus
