### ISSUE TITLE
[BUG] 1.36 A lot higher than the VR experience when replaying (Dr. Schmid)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#19]
**Describe the Bug:**

In reviewing the recorded session, the vantage point is a lot higher than the VR experience. Was this on purpose?

**Comment by SchubyDong** [comment]
We designed this as 3rd person view angle to get a more clear view for the observer. We can also change the record position if this pos looks not that good

**Comment by smallelephant9516** [comment]
I think our newest version of the angle for the replay session is good. It actually indicates that we are on 3rd person view angle. In a higher position, we will have a wider view and it is easier for users to gain an overall understanding of the performance. So, I close this issue.
