### ISSUE TITLE
[BUG & invalid] 1.38 Skipping the step of wearing the goggle.

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#20]
We can skip the step of wearing the goggle in the safety feature before we start. Also, I didn't hear the indication of wearing the goggle.

**Comment by Wandayu** [comment]
> We can skip the step of wearing the goggle in the safety feature before we start. Also, I didn't hear the indication of wearing the goggle.

I also meet this problem. I didn't wear the goggle and just transferred all the items on the cart, then the program went to the next scene

**Comment by huang841** [comment]
Problem solved.

**Comment by smallelephant9516** [comment]
The problem is not solved in 1.39 version

**Comment by smallelephant9516** [comment]
The problem is solved
