### ISSUE TITLE
[BUG] 1.38 Wrong position of the container in tank in the initial menu scene

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#21]
**Describe the Bug**

In the initial menu scene, the container in the large tank is not in the tank, but outside.
![1](https://user-images.githubusercontent.com/31882005/93928789-dedf2680-fce8-11ea-80af-6de56c40b259.png)

**Comment by SchubyDong** [comment]
The storage dewar was not supposed to exist in the menu scene. We have deleted it to make sure the menu scene is clear enough
