### ISSUE TITLE
[BUG] 1.38 Wrong position of a red arrow when I put back the tip

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#22]
**Describe the Bug**

When I put back the ethane tip, there is a red arrow which is in the wrong position I think, between the work station and ethane tank.
![2](https://user-images.githubusercontent.com/31882005/93928929-13eb7900-fce9-11ea-8ef0-9ed45d202ce5.png)

**Comment by SchubyDong** [comment]
We have redesigned the position and scale of most of the UI arrows. Now this problem has been solved, so as other UI problems like this
