### ISSUE TITLE
[Invalid] The texture for the container, plastic tube, petri dish, and color for the gas. 

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#24]
Brenda suggests that the texture for the container, plastic tube, and petri dish is not correct. And also the gas goes out from the ethane tips should not be black.

**Comment by smallelephant9516** [comment]
I will fix the problem of the texture and for the gas from ethane tips, please let @SchubyDong fix it in the unreal environment.

**Comment by smallelephant9516** [comment]
It seems that @Wandayu has some solutions in #12

**Comment by huang841** [comment]
We have already figure out this solution, Jiahui will fix it once his laptop work soon.
