### ISSUE TITLE
[Feature Request] A bigger arrow for the UI

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#25]
Brenda thinks that we need to have a bigger arrow for the UI generally to make it more obvious.

**Comment by SchubyDong** [comment]
This problem is solved as we mentioned previously.

**Comment by SchubyDong** [comment]
> This problem is solved as we mentioned previously.

Reference: 1.38 Wrong position of a red arrow when I put back the tip #22

**Comment by SchubyDong** [comment]
We have enlarged the UI scale. As we can see in the ethane tank
