### ISSUE TITLE
[Feature Request] 1.38 In-Project function that allows to take screenshot

### ISSUE THREAD

**Issue by SchubyDong** [CryoVR/CryoVR_Vitrobot#28]

**Comment by SchubyDong** [comment]
We found a function in Vive system, the screenshots are saved in Steam folder. Now we are looking for a way to get them.

**Comment by SchubyDong** [comment]
Game tips in both our game and website

**Comment by SchubyDong** [comment]
On Monday we tested it on Vive Cosmos Controller. The shortcut-key we have for Vive and Vive-pro controllers doesn't work for Cosmos. We will think about another way to make sure the screenshot function works for all versions of controllers

**Comment by wjiang** [comment]
Need an audio or graphic instruction in the game or a text instruction in the installation procedure to tell the user how to take a screenshot
