### ISSUE TITLE
[Experience] Spider need to be taken off before put it on the platform

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#29]
The spider should be taken off before it is put on the platform, the screenshot below is wrong.
![image](https://user-images.githubusercontent.com/52638056/96189743-14a1b480-0f0f-11eb-9de3-068235167eb1.png)

**Comment by SchubyDong** [comment]
We now remove the spider after the cooling progress is finished. One thing that needs to be mentioned is now it's removed automatically. If we need to stress this step we can add another step that allows users to remove it. It's solved but I will leave this question as opened for future discussion

**Comment by SchubyDong** [comment]
Seems it works without any other concentration, I will close this issue
