### ISSUE TITLE
Add transfering liquid sample step in preperation level

### ISSUE THREAD

**Issue by SchubyDong** [CryoVR/CryoVR_Vitrobot#34]
The liquid sample just appears in the Eppendorf tube rack on the desktop later. It should be transferred from the cart, like all the other user items.

**Comment by SchubyDong** [comment]
We realized that there was some model problem where the pivot had offset. I have asked Dayu's help to get access to the model from our lab's desktop.

**Comment by SchubyDong** [comment]
The function has been added. Only the model and hand gesture while holding it need to be refined

**Comment by SchubyDong** [comment]
The new model with the correct pivot has been assigned.

**Comment by smallelephant9516** [comment]
We didn't see the step of adding the liquid sample in the preparation level.
