### ISSUE TITLE
Add step of putting back all items_by Dr. Schmid

### ISSUE THREAD

**Issue by SchubyDong** [CryoVR/CryoVR_Vitrobot#37]
After the protocol is done, the user MUST remove everything they brought into the freezing room. Put everything back on the cart. No gloves, goggles or labcoat left out, or still wearing them outside the freezing room (good practice for BSL2!). A trash can for gloves, eppendorf tubes, etc. would be good. Our Biosafety person has more complaints about this clutter than anything else!

**Comment by SchubyDong** [comment]
We have added this feature to our newest version. It's ready to have some test to find potential enhancement

**Comment by smallelephant9516** [comment]
I didn't see this step in 1.44 version
