### ISSUE TITLE
[BUG] 1.34 The platform is raising before raising the plunger.

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#39]
After I pressed the "START" button on Vitrobot screen, the platform raised, but the plunger didn't. So I pressed another time and the plunger raised. So when I pressed the "CONTINUE" button later, the platform fell first and the procedure seemed to stop.
I have tried two times, and it happened in both of them.

![20201116181933_1](https://user-images.githubusercontent.com/31882005/99293485-b79c6580-2810-11eb-93da-5443c52b78d8.jpg)

**Comment by SchubyDong** [comment]
We now try to restrict the button pressing during specific steps to prevent this condition. It works in the tutorial mode now.

**Comment by smallelephant9516** [comment]
This problem has been fixed
