### ISSUE TITLE
[Bug]1.34 Some UI issues

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#40]
![image](https://user-images.githubusercontent.com/52638056/99328665-935d7a80-284a-11eb-8901-d04c4983ce24.png)
There is a highlight for the stylus when we are not supposed to use it. It is on the step when we using the pipette to take the sample. 
![image](https://user-images.githubusercontent.com/52638056/99328744-bab44780-284a-11eb-9e08-4788d9b96cef.png)
The red highlight color for the "Start process" does not disappear when we finish clicking the button

**Comment by SchubyDong** [comment]
We have fixed this bug in tutorial mode

**Comment by smallelephant9516** [comment]
This problem has been fixed
