### ISSUE TITLE
LED Screen UI Elements

### ISSUE THREAD

**Issue by SchubyDong** [CryoVR/CryoVR_Vitrobot#42]
![image](https://user-images.githubusercontent.com/36869660/100089695-1d47ad80-2e20-11eb-9e9d-470fa602e793.png)

We have added some UI elements to the Vitrobot LED screen. Now it functionally works but the texture looks not perfect as shown above. If you have some opinions or ideas about it please leave comments in this issue. New screenshots form real Vitrobot with higher resolution may be required in the future.

**Comment by smallelephant9516** [comment]
I will refine this LED screen using the photoshop to make the text more clear.

**Comment by smallelephant9516** [comment]
![More options](https://user-images.githubusercontent.com/52638056/100682478-2b2b9000-3344-11eb-93ce-100b56ae7e88.png)

Here is the new LED screen edited by the photoshop, I think for the numbers, it is better to use the vector image of the number in the unreal engine
