### ISSUE TITLE
Move the temperate storage silver bucket closer to the work station. 

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#44]
Kadir proposed that we need to move the temperate storage silver bucket closer to the workstation and then transfer the grid. So, we need the bucket movable to make us able to move the bucket close to the workstation.

**Comment by SchubyDong** [comment]
The user now and decide where to put the bucket at the beginning of the game(in the preparation step). And we make it not moveable during the main procedure to prevent more bugs. I think the user can put it in the best position they think after the first round of training. We can discuss the necessity that we let users move it during the game

**Comment by SchubyDong** [comment]
Make it moveable/portable like in the real world.

**Comment by smallelephant9516** [comment]
We still want this feature to be implemented.
