### ISSUE TITLE
The 2 progress bar overlap together. 

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#45]
The progress bar of adding liquid nitrogen and adding ethane are stack to each other. 
![image](https://user-images.githubusercontent.com/52638056/100164985-1dc75f00-2e87-11eb-9504-6f3f11e22b47.png)
![image](https://user-images.githubusercontent.com/52638056/100164998-21f37c80-2e87-11eb-9da9-aa0f381f89d6.png)

**Comment by SchubyDong** [comment]
We made them visible to test the potential UI improvement and forgot to make them invisible again... Now the bug has been fixed
