### ISSUE TITLE
[Experience] 1.36 Is the model in the wrong place? (By Dr.Chen)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#5]
**Describe the Experience:**

When I start up, the start position is in a pretty wired direcction - I was standing at the side of the start menu. I have to move and turn to face the manu.

Also, the desk seems very high - I basically facing the transparent window of the Vitrobot. Is that correct?

**Comment by SchubyDong** [comment]
The start location is based on the user's room setting by himself. As for this problem, we recommend resetting the room setting in steamVR with correct parameters...

**Comment by smallelephant9516** [comment]
I agree, for me, the menu is too close to my starting position, I have to go back for a few steps to get to the optimal position to see the menu.
