### ISSUE TITLE
PC - objects fly away

### ISSUE THREAD

**Issue by chenyingjie** [CryoVR/CryoVR_Vitrobot#51]
I meet two cases that objects fly away.
One is the pipet. While I take the liquid nitrogen tank to the workstation, the tank may touch the pipet. Pipet fly away horizontally to far right.

One is the ethane tank tips. I tried to grab it, but it fly away - still move with my hand, but in a distance.

**Comment by chuzcjoe** [comment]
Fixed Pipette fly-away issue.
