### ISSUE TITLE
PC - Ethane tank valve

### ISSUE THREAD

**Issue by chenyingjie** [CryoVR/CryoVR_Vitrobot#52]
I can not open the valve of the Ethane tank.

**Comment by chuzcjoe** [comment]
It is a keyboard control event. I can also make it a mouse click event.

**Comment by chenyingjie** [comment]
Add the mouse event. Only use keyboard event when absolutely necessary.


Best,

Yingjie Victor Chen

Sent from my iPhone

On Dec 15, 2020, at 4:46 AM, Joe <notifications@github.com> wrote:

﻿

It is a keyboard control event. I can also make it a mouse click event.

**Comment by chuzcjoe** [comment]
Added mouse click event.
