### ISSUE TITLE
PC version - Interaction

### ISSUE THREAD

**Issue by chenyingjie** [CryoVR/CryoVR_Vitrobot#59]
I managed to click on the 2nd object after press "space" bar without cursor.

Then it is very hard to release it. Should I press "space" bar again? 

Also very hard to pick up small things, e.g. the cap of the drawer, the valve handle...

**Comment by chuzcjoe** [comment]
Once the cross-shape cursor is visible to users, it would be easy to aim those small objects and pick them up.
