### ISSUE TITLE
[BUG] 1.36 Unknow red arrow in one round (By Dr.Chen)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#6]
**Describe the Bug:**

In one round, there is a red arrow at the left side of virtobot reminding me to put on something. But I can never find it. Maybe the goggle?

**Comment by huang841** [comment]
We test many times for this bug, but we don't find any problems here. Maybe we need more details about this bug report.

**Comment by smallelephant9516** [comment]
I didn't meet this problem either after many times of practicing. Maybe more information from Dr. Chen
