### ISSUE TITLE
Instruction pause issue with Vitrobot Version1.55

### ISSUE THREAD

**Issue by CherynJ** [CryoVR/CryoVR_Vitrobot#68]
![image](https://user-images.githubusercontent.com/48228625/111201944-b0f0e580-8599-11eb-8cf4-fb5d0e0b1fe4.png)
After moving everything from the cart to the desk, the instructions not going to the next step.

**Comment by SchubyDong** [comment]
This may be caused by a failure of collision detection. I may enlarge the collision boxes of them to make those detections more sensitive.

**Comment by smallelephant9516** [comment]
I agree with that, please enlarge the collision box, in the current version, it is still a little bit hard to go to the next step.

**Comment by smallelephant9516** [comment]
It is the same problem with #57

**Comment by smallelephant9516** [comment]
I think it is much better now
