### ISSUE TITLE
Directly goes to the last step

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#69]
For the vitrobot version 1.55, it is good that @SchubyDong add a clean up step. However, after we finish the preparation level, it directly goes to the this step.
This is after I finish the preparation level.
![image](https://user-images.githubusercontent.com/52638056/111257707-048f1d80-85f2-11eb-8ff2-f32466e9966b.png)

**Comment by SchubyDong** [comment]
I have fixed the bug by editing the start step in the main level scene. Please test it in the next patch

**Comment by smallelephant9516** [comment]
Fixed
