### ISSUE TITLE
[Feature Request] 1.36 Feedback on wearing goggle (By Dr.Chen)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#7]
**Describe the Request:**

I do not know if I have put on goggle or not after I put it close to my face. I think you can create something, e.g. a frame show up in front of you for couple seconds, then disapear.

**Comment by SchubyDong** [comment]
We have added a sound hint to this step, as well as some other steps which are lack of indication.

**Comment by smallelephant9516** [comment]
I still don't hear the sound hint when wearing the goggle.

**Comment by Wandayu** [comment]
> I still don't hear the sound hint when wearing the goggle.

I also cannot hear the sound hint when I wear the goggle in v1.38
