### ISSUE TITLE
[Experience] 1.36 No enough hint about the work station in the hood (By Dr.Chen)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#8]
**Describe the Experience:**

The hint asked me to take the work station from the hood... I looked around can not find it. No hint either.  Luckly I move my head to the cabin and find it. There should be a more obvious visual hint for it.

**Comment by smallelephant9516** [comment]
I could identify where the hood is as it is big, also there is visual indication UI for the workstation. But I do agree with Dr. Chen, probably more text or voice indication saying the hood or workstation on the left side?

**Comment by smallelephant9516** [comment]
It seems that Brenda also meets this problem, we need a UI to indicate the location of the hood and lab coat because all these things are in the peripheral vision of our eyes.

**Comment by SchubyDong** [comment]
Problem solved as mentioned previously
Reference: 1.38 Wrong position of a red arrow when I put back the tip #22
