### ISSUE TITLE
The problem of putting the items back to the cart

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Vitrobot#82]
![image](https://user-images.githubusercontent.com/52638056/111847937-4ebd1b00-88e0-11eb-9e7b-3e9ffd7b0389.png)
On the last step, when I put all the items back, it does not go to the next step (The small silver dewar is not there because I throw it away to see what would happened)

**Comment by SchubyDong** [comment]
Ideally, all the devices that need to be cleaned should be on the cart at the same time to trigger the next step. This is to prevent participants put the device on the cart and then put it back on the desk. I'm not so sure if this is the problem that stops you.
