### ISSUE TITLE
[BUG] 1.36 Float work station on the vitrobot (By Dr.Chen)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#9]
**Describe the Bug:**

I accidently put the workstation on the vitrobot. Then the logic became wired. I can move the vitrobot out, but it will stay float in what ever position I put it.

**Comment by huang841** [comment]
This bug is caused by the steps we set for test before, we now change the steps in right logic to fit the requirement. [Fixed]

**Comment by smallelephant9516** [comment]
This seems to be fixed, I didn't meet this problems anymore.
