### ISSUE TITLE
the yellow tube rack is on the right as opposed to left. (Vitrobot_SOP)

### ISSUE THREAD

**Issue by CherynJ** [CryoVR/CryoVR_Vitrobot#96]
<img width="1121" alt="Screen Shot 2021-05-08 at 1 58 18 PM" src="https://user-images.githubusercontent.com/48228625/117548911-73429300-b005-11eb-9f90-9662cef5a9ed.png">

**Comment by smallelephant9516** [comment]
This is still a problem
